### ISSUE TITLE
Add light/dark support to samples and menus

### ISSUE THREAD

**Issue by greggman** [webgpu/webgpu-samples#392]
The menus are currently always dark on light

<img width="284" alt="Screenshot 2024-03-11 at 13 45 15" src="https://github.com/webgpu/webgpu-samples/assets/234804/c889a18f-e605-4be6-88bc-cfae05467409">

They should probably be responsive to the user's preferences

1. Put

   ```css
   :root {
     color-scheme: light dark;
   }
   ```

   in `styles.css` and in all the `sample/**/index.html` files. This makes the browser choose light are dark colors based on the user's preferences for not just the background color but also for scrollbars, `<input type="???">` etc...

2. add variables for colors in the `styles.css` and use them where appropriate

   ```css
   :root {
     /* these are the light colors */
     --some-color: #fe803f;
     --some-other-color: #fe803f;
   }
   @media (prefers-color-scheme: dark) {
     /* these are the dark colors */
     :root {
       --some-color: #2e401f;
       --some-other-color: #2e401f;
     }
   }
   ```

   then use the variables where appropriate

   ```css
   [data-tooltip]::after {
     background-color: var(--some-color);
     ...
   ```

   Less colors = better

3. The `<iframe>` must have a white background
 
   Pages default to white. Pages in the iframe may be external and may default to black text so we can't se the `<iframe>`'s color to anything other than white else it may be incompatible with the sample. For the samples in this repo, see (1) above.
